#!/usr/bin/env bash

# Constants
WORKING_DIR=./working

RASPIOS_IMAGE_NAME=raspios
RASPIOS_IMAGE_PATH=$WORKING_DIR/$RASPIOS_IMAGE_NAME.img
RASPIOS_IMAGE_XZ_PATH=$RASPIOS_IMAGE_PATH.xz

BASE_IMAGE_NAME=maslab-base
BASE_IMAGE_PATH=$WORKING_DIR/$BASE_IMAGE_NAME.img

TEAM_IMAGE_NAME=maslab-team
TEAM_IMAGE_PATH=$WORKING_DIR/$TEAM_IMAGE_NAME.img