#!/usr/bin/env bash

# Constants
BASE_IMAGE_DIR=./base-image

RASPIOS_IMAGE_NAME=raspios
RASPIOS_IMAGE_PATH=$BASE_IMAGE_DIR/$RASPIOS_IMAGE_NAME.img
RASPIOS_IMAGE_XZ_PATH=$RASPIOS_IMAGE_PATH.xz

BASE_IMAGE_NAME=maslab-base
BASE_IMAGE_PATH=$BASE_IMAGE_DIR/$BASE_IMAGE_NAME.img
BASE_IMAGE_XZ_PATH=$BASE_IMAGE_PATH.xz